---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: moodle-autoscale
  namespace: moodle
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moodle-dep
  targetCPUUtilizationPercentage: 50
