---
apiVersion : apps/v1
kind: Deployment
metadata:
    name: moodle-dep
    namespace: moodle
    labels:
      app: moodle
spec:
   replicas: 1
   selector:
     matchLabels:
       app: moodle
       tier: frontend
   template:
     metadata:
        labels:
           app: moodle
           tier: frontend
     spec:
        containers:
        - name: moodle-dep
          image: bitnami/moodle
          ports:
          - containerPort: 80
            name: moodle
          volumeMounts:
            - name: moodle-pvc
              mountPath: /var/www
          env:
            - name: MOODLE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mo-db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MOODLE_DATABASE_USER
              value: bn_moodle
            - name: MOODLE_DATABASE_NAME
              value: bitnami_moodle
            - name: MARIADB_HOST
              value: mysql-svc
            - name: MARIADB_PORT_NUMBER
              value: "3306"

        volumes:
         - name: moodle-pvc
           persistentVolumeClaim:
            claimName: moodle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodle-svc
  namespace: moodle
  labels:
    app: moodle
spec:
  type: LoadBalancer
  selector:
    app: moodle
    tier: frontend
    env: test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
