apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

