---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress-dep
    tier: frontend
    env: test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

